# -*- coding: utf-8 -*-
"""SHA_3_complete.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sqZwyZ8p-cTrYwtwplFS-zNQawZK7TIi
"""

import hashlib
import csv
import re

def sha3_encrypt(input_string):
    sha3 = hashlib.sha3_256()
    sha3.update(input_string.encode('utf-8'))
    encrypted_string = sha3.hexdigest()

    encrypted_string = re.sub(r'[0-9]', '', encrypted_string).lower()

    return encrypted_string

data = []

while True:
    name = input("Enter a name (or type 'exit' to quit and save data till here in CSV): ")

    if name.lower() == 'exit':
        break

    dob = input("Enter a date of birth (dd/mm/yyyy): ")

    dob = '/'.join(dob.split('/')[::-1])

    encrypted_name = sha3_encrypt(name)
    encrypted_dob = sha3_encrypt(dob)

    data.append([name, dob, encrypted_name, encrypted_dob])

# Define the CSV file name
csv_file = "sha3_encrypted_data.csv"

# Write the data to a CSV file
with open(csv_file, 'w', newline='') as file:
    writer = csv.writer(file)

    # Write the header row
    writer.writerow(["Name", "Date of Birth (dd/mm/yyyy)", " Hashed Name ", "Hashed DOB "])

    # Write the data
    writer.writerows(data)

print(f"Data saved successfully to {csv_file}")